"""add column dota2_id in table Gamers

Revision ID: 51d38b1b6cc1
Revises: b226ec680736
Create Date: 2024-06-08 11:59:34.610575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51d38b1b6cc1"
down_revision: Union[str, None] = "b226ec680736"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gamers", sa.Column("dota2_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "gamers", ["dota2_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gamers", type_="unique")
    op.drop_column("gamers", "dota2_id")
    # ### end Alembic commands ###
