"""add type column for table tournaments

Revision ID: ec9eb9cc62df
Revises: 48d2fee40854
Create Date: 2024-05-27 12:23:59.571982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec9eb9cc62df"
down_revision: Union[str, None] = "48d2fee40854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tournaments", sa.Column("type", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournaments", "type")
    # ### end Alembic commands ###
